name: workout_skripsi_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17
  month_picker_dialog: ^6.0.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/exercise/
    - lib/assets/equipments/
    - lib/assets/icon/

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/appicon.jpeg"
