name: flutter_application_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^0.13.6
  shared_preferences: ^2.2.2
  get: ^4.6.6
  flutter_markdown: ^0.6.17


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/exercise/
    - lib/assets/equipments/

  uses-material-design: true
